/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gradle.develocity.agent.api.adapters;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
